# Generated by Django 4.1.2 on 2023-05-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=500)),
                ('runtime', models.IntegerField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
